### ISSUE TITLE
Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by quentingosset** [jakubroztocil/cloudtunes#23]
I have this error : 

root@u12-49330:/data# git clonegit@github.com:jakubroztocil/cloudtunes.git
git: 'clonegit@github.com:jakubroztocil/cloudtunes.git' is not a git command. See 'git --help'.
root@u12-49330:/data# git clone git@github.com:jakubroztocil/cloudtunes.git
Cloning into 'cloudtunes'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists

your github is still good?

**Comment by myasirhashmi** [comment]
Thanks that saved my night. Cloning over HTTPS solved my issue

**Comment by sushilck** [comment]
Thank you

**Comment by monicarajasekaran** [comment]
I keep getting the same error even after cloning over https. Any idea why ?

**Comment by viviraj20** [comment]
hi 

I have the similar error 
when i run the puppet .
#############################
Host key verification failed.
       fatal: Could not read from remote repository.
       
       Please make sure you have the correct access rights
       and the repository exists.
############################
i have my keys on my vm and my git is using the same key 

please help me out 
Thanks in ADVANCE

**Comment by mathsyouth** [comment]
@o-shabashov That works! Thanks so much.

**Comment by akotranza** [comment]
You'll get this error on windows even if you have puttygen'd a ppk from your github_rsa key and added the ppk in peagent... until you visit github.com in putty. A good reason not to use windows, I suppose.

**Comment by Coder000111** [comment]
**Thanks**

**Comment by SadieYuCN** [comment]
1. eval `ssh-agent`
2. ssh-add ~/.ssh/your ssh key
3. enter you ssh key pwd
4. run any git command you want

**Comment by wangxiaoyao** [comment]
1 删除.ssh 下面的known_hosts   文件
2 删除github上的密钥，并重新生成和添加密钥 
[3](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)

3  还是不成功，就是你家的网络问题。 建议换一个网络。 并且github是不需要翻墙的。

**Comment by icetaste** [comment]
it works

**Comment by dtoubelis** [comment]
BTW, the workaround suggested by @SadieYuCN works! You can also kill the ssh-agent after doing `git pull` just once and everything returns back to normal.

**Comment by akarteharish** [comment]
Can anyone please solve my problem.... I am getting following error while cloning from github..

aadarsh@aadarsh-OptiPlex-9020:~/Desktop$ git clone git@github.com:p4lang/behavioral-model.git bmv2
Cloning into 'bmv2'...
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by unnir** [comment]
I solved that using answer from [here](https://stackoverflow.com/questions/25927914/git-error-please-make-sure-you-have-the-correct-access-rights-and-the-reposito):

first:
`$ eval "$(ssh-agent -s)"
`
next:
`$ ssh-add
`

**Comment by vieckys** [comment]
@jakubroztocil  it worked. thanks !

**Comment by anRoswell** [comment]
Hola para ser mas exacto el comando es 

**git clone https://github.com/YOUR-USERNAME/YOUR-REPOSITORY esto para importar**

**git push --mirror https://github.com/YOUR-USERNAME/YOUR-REPOSITORY esto para exportar**

Mucho me dure buscando q se habia actualizado los comandos, espero alguien le sirva, esto lo utilice para trabajar con Ionic.

**Comment by zhanyige** [comment]
[When I type this command below]:
git clone git@psr.pku.edu.cn:kjlee/bear.git

[Then, here are the output]
正克隆到 'bear'...
ssh: connect to host psr.pku.edu.cn port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.



I have ssh key done.

**Comment by azizsallam** [comment]
I spent  3 hours  and work around  i did not find a solution the remote repo already exist   i wonder why?
 access rights denied

**Comment by MuffinCrow** [comment]
> The instructions have been updated to clone over HTTPS. This should work with no issues:
> 
> ```shell
> $ git clone https://github.com/jakubroztocil/cloudtunes.git
> ```

Yo I am so glad I found this. Been trying to do school project and youtube aint helping. Thanks man!

**Comment by SandHani45** [comment]
unable to access 'https://github.com/jakubroztocil/cloudtunes.git/': Could not resolve host: github.com``
im getting this error when im going to push code into to git can you help  me any one

**Comment by carlos-urena** [comment]
had this problem on a mac and I discovered that simply by accessing the repository once from github desktop allows me to clone from the command line later

**Comment by hackerghost93** [comment]
In windows 10 I used CWD in admin mode, as git bash didn't said this same error over and over.

**Comment by jakubroztocil** [comment]
Please refer to GitHub documentation on how to clone a repo and how to resolve issues:

https://help.github.com/articles/cloning-a-repository-from-github/
